apiVersion: apps/v1
kind: Deployment
metadata:
  name: slots
  labels:
    app: slots
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1722956080676
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slots
  template:
    metadata:
      labels:
        app: slots
    spec:
      containers:
        - name: slots
          image: acrworkflow1722956080676.azurecr.io/image-workflow-1722956080676:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
