apiVersion: v1
kind: Service
metadata:
  name: myFlow
  namespace: namespace-workflow-1722955762279
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: myFlow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000