apiVersion: v1
kind: Service
metadata:
  name: slots
  namespace: namespace-workflow-1722956080676
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: slots
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000